export const SECURITY_SUBCHECKS = {
  NOT_HTTPS: 'not-https',
  MIXED_CONTENT: 'mixed-content',
  MISSING_SRI: 'missing-sri',
  INSECURE_FORM: 'insecure-form',
  MISSING_CSP: 'missing-csp',
  CSP_REPORT_ONLY: 'csp-report-only',
  CSP_UNSAFE_INLINE_SCRIPT: 'csp-unsafe-inline-script',
  CSP_UNSAFE_EVAL_SCRIPT: 'csp-unsafe-eval-script',
  CSP_SCRIPT_SRC_WILDCARD: 'csp-script-src-wildcard',
  CSP_OBJECT_SRC_WILDCARD: 'csp-object-src-wildcard',
  CSP_MISSING_OBJECT_SRC: 'csp-missing-object-src',
  CSP_MISSING_DEFAULT_SRC: 'csp-missing-default-src',
  CSP_MISSING_FRAME_ANCESTORS: 'csp-missing-frame-ancestors',
  MISSING_X_FRAME_OPTIONS: 'missing-x-frame-options',
  MISSING_REFERRER_POLICY: 'missing-referrer-policy',
  MISSING_HSTS: 'missing-hsts',
  HSTS_INVALID: 'hsts-invalid',
  HSTS_SHORT_MAX_AGE: 'hsts-short-max-age',
  HSTS_MISSING_SUBDOMAINS: 'hsts-missing-subdomains',
  HSTS_MISSING_PRELOAD: 'hsts-missing-preload',
  MISSING_X_CONTENT_TYPE_OPTIONS: 'missing-x-content-type-options',
  INVALID_X_CONTENT_TYPE_OPTIONS: 'invalid-x-content-type-options',
  MISSING_PERMISSIONS_POLICY: 'missing-permissions-policy',
  MISSING_COOP: 'missing-coop',
  MISSING_COEP: 'missing-coep',
  MISSING_CORP: 'missing-corp',
  SERVER_VERSION_DISCLOSURE: 'server-version-disclosure',
  X_POWERED_BY_DISCLOSURE: 'x-powered-by-disclosure',
  COOKIE_MISSING_SECURE: 'cookie-missing-secure',
  COOKIE_MISSING_HTTP_ONLY: 'cookie-missing-httponly',
  COOKIE_MISSING_SAME_SITE: 'cookie-missing-samesite',
  NO_HTTPS_REDIRECT: 'no-https-redirect',
  MISSING_SECURITY_TXT: 'missing-security-txt',
} as const;

export type SecuritySubCheck = typeof SECURITY_SUBCHECKS[keyof typeof SECURITY_SUBCHECKS];
